<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {


        $countries = [
            array('id' => '1','name_ar' => 'أندورا','name_fr' => 'Andorre','name_en' => 'Andorra','code' => 'country-ad.svg'),
            array('id' => '2','name_ar' => 'الإمارات العربية المتحدة','name_fr' => 'Emirats Arabes Unis','name_en' => 'United Arab Emirates','code' => 'country-ae.svg'),
            array('id' => '3','name_ar' => 'أفغانستان','name_fr' => 'L\'Afghanistan','name_en' => 'Afghanistan','code' => 'country-af.svg'),
            array('id' => '4','name_ar' => 'أنتيغوا وبربودا','name_fr' => 'Antigua-et-Barbuda','name_en' => 'Antigua and Barbuda','code' => 'country-ag.svg'),
            array('id' => '5','name_ar' => 'أنغيلا','name_fr' => 'Anguilla','name_en' => 'Anguilla','code' => 'country-ai.svg'),
            array('id' => '6','name_ar' => 'ألبانيا','name_fr' => 'Albanie','name_en' => 'Albania','code' => 'country-al.svg'),
            array('id' => '7','name_ar' => 'أرمينيا','name_fr' => 'Arménie','name_en' => 'Armenia','code' => 'country-am.svg'),
          //  array('id' => '8','name_ar' => 'جزر الأنتيل الهولندية','name_fr' => 'Antilles néerlandaises','name_en' => 'Netherlands Antilles','code' => 'country-an.svg'),
            array('id' => '9','name_ar' => 'أنغولا','name_fr' => 'Angola','name_en' => 'Angola','code' => 'country-ao.svg'),
            array('id' => '10','name_ar' => 'الأرجنتين','name_fr' => 'Argentine','name_en' => 'Argentina','code' => 'country-ar.svg'),
            array('id' => '11','name_ar' => 'النمسا','name_fr' => 'L\'Autriche','name_en' => 'Austria','code' => 'country-at.svg'),
            array('id' => '12','name_ar' => 'أستراليا','name_fr' => 'Australie','name_en' => 'Australia','code' => 'country-au.svg'),
            array('id' => '13','name_ar' => 'أروبا','name_fr' => 'Aruba','name_en' => 'Aruba','code' => 'country-aw.svg'),
            array('id' => '14','name_ar' => 'أذربيجان','name_fr' => 'Azerbaïdjan','name_en' => 'Azerbaijan','code' => 'country-az.svg'),
            array('id' => '15','name_ar' => 'البوسنة والهرسك','name_fr' => 'Bosnie Herzégovine','name_en' => 'Bosnia and Herzegovina','code' => 'country-ba.svg'),
            array('id' => '16','name_ar' => 'بربادوس','name_fr' => 'La Barbade','name_en' => 'Barbados','code' => 'country-bb.svg'),
            array('id' => '17','name_ar' => 'بنغلاديش','name_fr' => 'Bangladesh','name_en' => 'Bangladesh','code' => 'country-bd.svg'),
            array('id' => '18','name_ar' => 'بلجيكا','name_fr' => 'Belgique','name_en' => 'Belgium','code' => 'country-be.svg'),
            array('id' => '19','name_ar' => 'بوركينا فاسو','name_fr' => 'Burkina Faso','name_en' => 'Burkina Faso','code' => 'country-bf.svg'),
            array('id' => '20','name_ar' => 'بلغاريا','name_fr' => 'Bulgarie','name_en' => 'Bulgaria','code' => 'country-bg.svg'),
            array('id' => '21','name_ar' => 'البحرين','name_fr' => 'Bahreïn','name_en' => 'Bahrain','code' => 'country-bh.svg'),
            array('id' => '22','name_ar' => 'بوروندي','name_fr' => 'Burundi','name_en' => 'Burundi','code' => 'country-bi.svg'),
            array('id' => '23','name_ar' => 'بنين','name_fr' => 'Bénin','name_en' => 'Benin','code' => 'country-bj.svg'),
            array('id' => '24','name_ar' => 'برمودا','name_fr' => 'Bermudes','name_en' => 'Bermuda','code' => 'country-bm.svg'),
            array('id' => '25','name_ar' => 'بروناي دار السلام','name_fr' => 'Brunei Darussalam','name_en' => 'Brunei Darussalam','code' => 'country-bn.svg'),
            array('id' => '26','name_ar' => 'بوليفيا','name_fr' => 'Bolivie','name_en' => 'Bolivia','code' => 'country-bo.svg'),
            array('id' => '27','name_ar' => 'البرازيل','name_fr' => 'Brésil','name_en' => 'Brazil','code' => 'country-br.svg'),
            array('id' => '28','name_ar' => 'الباهاما','name_fr' => 'Bahamas','name_en' => 'Bahamas','code' => 'country-bs.svg'),
            array('id' => '29','name_ar' => 'بوتان','name_fr' => 'Bhoutan','name_en' => 'Bhutan','code' => 'country-bt.svg'),
            array('id' => '30','name_ar' => 'بوتسوانا','name_fr' => 'Botswana','name_en' => 'Botswana','code' => 'country-bw.svg'),
            array('id' => '31','name_ar' => 'روسيا البيضاء','name_fr' => 'Biélorussie','name_en' => 'Belarus','code' => 'country-by.svg'),
            array('id' => '32','name_ar' => 'بليز','name_fr' => 'Belize','name_en' => 'Belize','code' => 'country-bz.svg'),
            array('id' => '33','name_ar' => 'كندا','name_fr' => 'Canada','name_en' => 'Canada','code' => 'country-ca.svg'),
            array('id' => '34','name_ar' => 'جزر كوكوس (كيلينغ)','name_fr' => 'Îles Cocos (Keeling)','name_en' => 'Cocos (Keeling) Islands','code' => 'country-cc.svg'),
            array('id' => '35','name_ar' => 'جمهورية الكونغو الديموقراطية','name_fr' => 'République Démocratique du Congo','name_en' => 'Democratic Republic of the Congo','code' => 'country-cd.svg'),
            array('id' => '36','name_ar' => 'جمهورية افريقيا الوسطى','name_fr' => 'République centrafricaine','name_en' => 'Central African Republic','code' => 'country-cf.svg'),
            array('id' => '37','name_ar' => 'الكونغو','name_fr' => 'Congo','name_en' => 'Congo','code' => 'country-cg.svg'),
            array('id' => '38','name_ar' => 'سويسرا','name_fr' => 'Suisse','name_en' => 'Switzerland','code' => 'country-ch.svg'),
            array('id' => '39','name_ar' => 'ساحل العاج (ساحل العاج)','name_fr' => 'Cote D\'Ivoire (Côte d\'Ivoire)','name_en' => 'Cote D\'Ivoire (Ivory Coast)','code' => 'country-ci.svg'),
            array('id' => '40','name_ar' => 'جزر كوك','name_fr' => 'les Îles Cook','name_en' => 'Cook Islands','code' => 'country-ck.svg'),
            array('id' => '41','name_ar' => 'تشيلي','name_fr' => 'Chili','name_en' => 'Chile','code' => 'country-cl.svg'),
            array('id' => '42','name_ar' => 'الكاميرون','name_fr' => 'Cameroun','name_en' => 'Cameroon','code' => 'country-cm.svg'),
            array('id' => '43','name_ar' => 'الصين','name_fr' => 'Chine','name_en' => 'China','code' => 'country-cn.svg'),
            array('id' => '44','name_ar' => 'كولومبيا','name_fr' => 'Colombie','name_en' => 'Colombia','code' => 'country-co.svg'),
            array('id' => '45','name_ar' => 'كوستا ريكا','name_fr' => 'Costa Rica','name_en' => 'Costa Rica','code' => 'country-cr.svg'),
            array('id' => '46','name_ar' => 'كوبا','name_fr' => 'Cuba','name_en' => 'Cuba','code' => 'country-cu.svg'),
            array('id' => '47','name_ar' => 'الرأس الأخضر','name_fr' => 'Cap-Vert','name_en' => 'Cape Verde','code' => 'country-cv.svg'),
            array('id' => '48','name_ar' => 'جزيرة الكريسماس','name_fr' => 'L\'île de noël','name_en' => 'Christmas Island','code' => 'country-cx.svg'),
            array('id' => '49','name_ar' => 'قبرص','name_fr' => 'Chypre','name_en' => 'Cyprus','code' => 'country-cy.svg'),
            array('id' => '50','name_ar' => 'جمهورية التشيك','name_fr' => 'République Tchèque','name_en' => 'Czech Republic','code' => 'country-cz.svg'),
            array('id' => '51','name_ar' => 'ألمانيا','name_fr' => 'Allemagne','name_en' => 'Germany','code' => 'country-de.svg'),
            array('id' => '52','name_ar' => 'جيبوتي','name_fr' => 'Djibouti','name_en' => 'Djibouti','code' => 'country-dj.svg'),
            array('id' => '53','name_ar' => 'الدنمارك','name_fr' => 'Danemark','name_en' => 'Denmark','code' => 'country-dk.svg'),
            array('id' => '54','name_ar' => 'دومينيكا','name_fr' => 'Dominique','name_en' => 'Dominica','code' => 'country-dm.svg'),
            array('id' => '55','name_ar' => 'جمهورية الدومنيكان','name_fr' => 'République Dominicaine','name_en' => 'Dominican Republic','code' => 'country-do.svg'),
            array('id' => '56','name_ar' => 'الجزائر','name_fr' => 'Algérie','name_en' => 'Algeria','code' => 'country-dz.svg'),
            array('id' => '57','name_ar' => 'الإكوادور','name_fr' => 'L\'Équateur','name_en' => 'Ecuador','code' => 'country-ec.svg'),
            array('id' => '58','name_ar' => 'استونيا','name_fr' => 'Estonie','name_en' => 'Estonia','code' => 'country-ee.svg'),
            array('id' => '59','name_ar' => 'مصر','name_fr' => 'Egypte','name_en' => 'Egypt','code' => 'country-eg.svg'),
            array('id' => '60','name_ar' => 'الصحراء الغربية','name_fr' => 'Sahara occidental','name_en' => 'Western Sahara','code' => 'country-eh.svg'),
            array('id' => '61','name_ar' => 'إريتريا','name_fr' => 'Erythrée','name_en' => 'Eritrea','code' => 'country-er.svg'),
            array('id' => '62','name_ar' => 'إسبانيا','name_fr' => 'Espagne','name_en' => 'Spain','code' => 'country-es.svg'),
            array('id' => '63','name_ar' => 'أثيوبيا','name_fr' => 'Ethiopie','name_en' => 'Ethiopia','code' => 'country-et.svg'),
            array('id' => '64','name_ar' => 'فنلندا','name_fr' => 'Finlande','name_en' => 'Finland','code' => 'country-fi.svg'),
            array('id' => '65','name_ar' => 'فيجي','name_fr' => 'Fidji','name_en' => 'Fiji','code' => 'country-fj.svg'),
            array('id' => '66','name_ar' => 'جزر فوكلاند (مالفيناس)','name_fr' => 'Iles Malouines (Malouines)','name_en' => 'Falkland Islands (Malvinas)','code' => 'country-fk.svg'),
            array('id' => '67','name_ar' => 'ولايات ميكرونيزيا الموحدة','name_fr' => 'États fédérés de Micronésie','name_en' => 'Federated States of Micronesia','code' => 'country-fm.svg'),
            array('id' => '68','name_ar' => 'جزر صناعية','name_fr' => 'Îles Féroé','name_en' => 'Faroe Islands','code' => 'country-fo.svg'),
            array('id' => '69','name_ar' => 'فرنسا','name_fr' => 'France','name_en' => 'France','code' => 'country-fr.svg'),
            array('id' => '70','name_ar' => 'الغابون','name_fr' => 'Gabon','name_en' => 'Gabon','code' => 'country-ga.svg'),
            array('id' => '71','name_ar' => 'بريطانيا العظمى (المملكة المتحدة)','name_fr' => 'Grande-Bretagne (UK)','name_en' => 'Great Britain (UK)','code' => 'country-gb.svg'),
            array('id' => '72','name_ar' => 'غرينادا','name_fr' => 'Grenade','name_en' => 'Grenada','code' => 'country-gd.svg'),
            array('id' => '73','name_ar' => 'جورجيا','name_fr' => 'Géorgie','name_en' => 'Georgia','code' => 'country-ge.svg'),
            array('id' => '74','name_ar' => 'غيانا الفرنسية','name_fr' => 'Guinée Française','name_en' => 'French Guiana','code' => 'country-gf.svg'),
            array('id' => '75','name_ar' => 'لا شيء','name_fr' => 'NUL','name_en' => 'NULL','code' => 'country-gg.svg'),
            array('id' => '76','name_ar' => 'غانا','name_fr' => 'Ghana','name_en' => 'Ghana','code' => 'country-gh.svg'),
            array('id' => '77','name_ar' => 'جبل طارق','name_fr' => 'Gibraltar','name_en' => 'Gibraltar','code' => 'country-gi.svg'),
            array('id' => '78','name_ar' => 'الأرض الخضراء','name_fr' => 'Groenland','name_en' => 'Greenland','code' => 'country-gl.svg'),
            array('id' => '79','name_ar' => 'غامبيا','name_fr' => 'Gambie','name_en' => 'Gambia','code' => 'country-gm.svg'),
            array('id' => '80','name_ar' => 'غينيا','name_fr' => 'Guinée','name_en' => 'Guinea','code' => 'country-gn.svg'),
            array('id' => '81','name_ar' => 'جوادلوب','name_fr' => 'La guadeloupe','name_en' => 'Guadeloupe','code' => 'country-gp.svg'),
            array('id' => '82','name_ar' => 'غينيا الإستوائية','name_fr' => 'Guinée Équatoriale','name_en' => 'Equatorial Guinea','code' => 'country-gq.svg'),
            array('id' => '83','name_ar' => 'اليونان','name_fr' => 'Grèce','name_en' => 'Greece','code' => 'country-gr.svg'),
            array('id' => '84','name_ar' => 'جورجيا وجزر ساندويتش','name_fr' => 'Géorgie du Sud et les îles Sandwich du Sud','name_en' => 'S. Georgia and S. Sandwich Islands','code' => 'country-gs.svg'),
            array('id' => '85','name_ar' => 'غواتيمالا','name_fr' => 'Guatemala','name_en' => 'Guatemala','code' => 'country-gt.svg'),
            array('id' => '86','name_ar' => 'غينيا بيساو','name_fr' => 'Guinée-Bissau','name_en' => 'Guinea-Bissau','code' => 'country-gw.svg'),
            array('id' => '87','name_ar' => 'غيانا','name_fr' => 'Guyane','name_en' => 'Guyana','code' => 'country-gy.svg'),
            array('id' => '88','name_ar' => 'هونغ كونغ','name_fr' => 'Hong Kong','name_en' => 'Hong Kong','code' => 'country-hk.svg'),
            array('id' => '89','name_ar' => 'هندوراس','name_fr' => 'Honduras','name_en' => 'Honduras','code' => 'country-hn.svg'),
            array('id' => '90','name_ar' => 'كرواتيا (هرفاتسكا)','name_fr' => 'Croatie (Hrvatska)','name_en' => 'Croatia (Hrvatska)','code' => 'country-hr.svg'),
            array('id' => '91','name_ar' => 'هايتي','name_fr' => 'Haïti','name_en' => 'Haiti','code' => 'country-ht.svg'),
            array('id' => '92','name_ar' => 'اليونان','name_fr' => 'Hongrie','name_en' => 'Hungary','code' => 'country-hu.svg'),
            array('id' => '93','name_ar' => 'أندونيسيا','name_fr' => 'Indonésie','name_en' => 'Indonesia','code' => 'country-id.svg'),
            array('id' => '94','name_ar' => 'أيرلندا','name_fr' => 'Irlande','name_en' => 'Ireland','code' => 'country-ie.svg'),
            array('id' => '96','name_ar' => 'الهند','name_fr' => 'Inde','name_en' => 'India','code' => 'country-in.svg'),
            array('id' => '97','name_ar' => 'العراق','name_fr' => 'Irak','name_en' => 'Iraq','code' => 'country-iq.svg'),
            array('id' => '98','name_ar' => 'إيران','name_fr' => 'Iran','name_en' => 'Iran','code' => 'country-ir.svg'),
            array('id' => '99','name_ar' => 'أيسلندا','name_fr' => 'Islande','name_en' => 'Iceland','code' => 'country-is.svg'),
            array('id' => '100','name_ar' => 'إيطاليا','name_fr' => 'Italie','name_en' => 'Italy','code' => 'country-it.svg'),
            array('id' => '101','name_ar' => 'جامايكا','name_fr' => 'Jamaïque','name_en' => 'Jamaica','code' => 'country-jm.svg'),
            array('id' => '102','name_ar' => 'الأردن','name_fr' => 'Jordan','name_en' => 'Jordan','code' => 'country-jo.svg'),
            array('id' => '103','name_ar' => 'اليابان','name_fr' => 'Japon','name_en' => 'Japan','code' => 'country-jp.svg'),
            array('id' => '104','name_ar' => 'كينيا','name_fr' => 'Kenya','name_en' => 'Kenya','code' => 'country-ke.svg'),
            array('id' => '105','name_ar' => 'قرغيزستان','name_fr' => 'Kirghizistan','name_en' => 'Kyrgyzstan','code' => 'country-kg.svg'),
            array('id' => '106','name_ar' => 'كمبوديا','name_fr' => 'Cambodge','name_en' => 'Cambodia','code' => 'country-kh.svg'),
            array('id' => '107','name_ar' => 'كيريباس','name_fr' => 'Kiribati','name_en' => 'Kiribati','code' => 'country-ki.svg'),
            array('id' => '108','name_ar' => 'جزر القمر','name_fr' => 'Comores','name_en' => 'Comoros','code' => 'country-km.svg'),
            array('id' => '109','name_ar' => 'سانت كيتس ونيفيس','name_fr' => 'Saint-Christophe-et-Niévès','name_en' => 'Saint Kitts and Nevis','code' => 'country-kn.svg'),
            array('id' => '110','name_ar' => 'كوريا الشمالية','name_fr' => 'Corée du Nord','name_en' => 'Korea (North)','code' => 'country-kp.svg'),
            array('id' => '111','name_ar' => 'كوريا، جنوب)','name_fr' => 'COREE DU SUD)','name_en' => 'Korea (South)','code' => 'country-kr.svg'),
            array('id' => '112','name_ar' => 'الكويت','name_fr' => 'Koweit','name_en' => 'Kuwait','code' => 'country-kw.svg'),
            array('id' => '113','name_ar' => 'جزر كايمان','name_fr' => 'Îles Caïmans','name_en' => 'Cayman Islands','code' => 'country-ky.svg'),
            array('id' => '114','name_ar' => 'كازاخستان','name_fr' => 'Le kazakhstan','name_en' => 'Kazakhstan','code' => 'country-kz.svg'),
            array('id' => '115','name_ar' => 'لاوس','name_fr' => 'Laos','name_en' => 'Laos','code' => 'country-la.svg'),
            array('id' => '116','name_ar' => 'لبنان','name_fr' => 'Liban','name_en' => 'Lebanon','code' => 'country-lb.svg'),
            array('id' => '117','name_ar' => 'القديسة لوسيا','name_fr' => 'Sainte-Lucie','name_en' => 'Saint Lucia','code' => 'country-lc.svg'),
            array('id' => '118','name_ar' => 'ليختنشتاين','name_fr' => 'Le Liechtenstein','name_en' => 'Liechtenstein','code' => 'country-li.svg'),
            array('id' => '119','name_ar' => 'سيريلانكا','name_fr' => 'Sri Lanka','name_en' => 'Sri Lanka','code' => 'country-lk.svg'),
            array('id' => '120','name_ar' => 'ليبيريا','name_fr' => 'Libéria','name_en' => 'Liberia','code' => 'country-lr.svg'),
            array('id' => '121','name_ar' => 'ليسوتو','name_fr' => 'Lesotho','name_en' => 'Lesotho','code' => 'country-ls.svg'),
            array('id' => '122','name_ar' => 'ليتوانيا','name_fr' => 'Lituanie','name_en' => 'Lithuania','code' => 'country-lt.svg'),
            array('id' => '123','name_ar' => 'لوكسمبورغ','name_fr' => 'Luxembourg','name_en' => 'Luxembourg','code' => 'country-lu.svg'),
            array('id' => '124','name_ar' => 'لاتفيا','name_fr' => 'Lettonie','name_en' => 'Latvia','code' => 'country-lv.svg'),
            array('id' => '125','name_ar' => 'ليبيا','name_fr' => 'Libye','name_en' => 'Libya','code' => 'country-ly.svg'),
            array('id' => '126','name_ar' => 'المغرب','name_fr' => 'Maroc','name_en' => 'Morocco','code' => 'country-ma.svg'),
            array('id' => '127','name_ar' => 'موناكو','name_fr' => 'Monaco','name_en' => 'Monaco','code' => 'country-mc.svg'),
            array('id' => '128','name_ar' => 'مولدوفا','name_fr' => 'La Moldavie','name_en' => 'Moldova','code' => 'country-md.svg'),
            array('id' => '129','name_ar' => 'مدغشقر','name_fr' => 'Madagascar','name_en' => 'Madagascar','code' => 'country-mg.svg'),
            array('id' => '130','name_ar' => 'جزر مارشال','name_fr' => 'Iles Marshall','name_en' => 'Marshall Islands','code' => 'country-mh.svg'),
            array('id' => '131','name_ar' => 'مقدونيا','name_fr' => 'Macédoine','name_en' => 'Macedonia','code' => 'country-mk.svg'),
            array('id' => '132','name_ar' => 'مالي','name_fr' => 'Mali','name_en' => 'Mali','code' => 'country-ml.svg'),
            array('id' => '133','name_ar' => 'ميانمار','name_fr' => 'Myanmar','name_en' => 'Myanmar','code' => 'country-mm.svg'),
            array('id' => '134','name_ar' => 'منغوليا','name_fr' => 'Mongolie','name_en' => 'Mongolia','code' => 'country-mn.svg'),
            array('id' => '135','name_ar' => 'ماكاو','name_fr' => 'Macao','name_en' => 'Macao','code' => 'country-mo.svg'),
            array('id' => '136','name_ar' => 'جزر مريانا الشمالية','name_fr' => 'Îles Mariannes du Nord','name_en' => 'Northern Mariana Islands','code' => 'country-mp.svg'),
            array('id' => '137','name_ar' => 'مارتينيك','name_fr' => 'Martinique','name_en' => 'Martinique','code' => 'country-mq.svg'),
            array('id' => '138','name_ar' => 'موريتانيا','name_fr' => 'Mauritanie','name_en' => 'Mauritania','code' => 'country-mr.svg'),
            array('id' => '139','name_ar' => 'مونتسيرات','name_fr' => 'Montserrat','name_en' => 'Montserrat','code' => 'country-ms.svg'),
            array('id' => '140','name_ar' => 'مالطا','name_fr' => 'Malte','name_en' => 'Malta','code' => 'country-mt.svg'),
            array('id' => '141','name_ar' => 'موريشيوس','name_fr' => 'Maurice','name_en' => 'Mauritius','code' => 'country-mu.svg'),
            array('id' => '142','name_ar' => 'جزر المالديف','name_fr' => 'Maldives','name_en' => 'Maldives','code' => 'country-mv.svg'),
            array('id' => '143','name_ar' => 'مالاوي','name_fr' => 'Malawi','name_en' => 'Malawi','code' => 'country-mw.svg'),
            array('id' => '144','name_ar' => 'المكسيك','name_fr' => 'Mexique','name_en' => 'Mexico','code' => 'country-mx.svg'),
            array('id' => '145','name_ar' => 'ماليزيا','name_fr' => 'Malaisie','name_en' => 'Malaysia','code' => 'country-my.svg'),
            array('id' => '146','name_ar' => 'موزمبيق','name_fr' => 'Mozambique','name_en' => 'Mozambique','code' => 'country-mz.svg'),
            array('id' => '147','name_ar' => 'ناميبيا','name_fr' => 'Namibie','name_en' => 'Namibia','code' => 'country-na.svg'),
            array('id' => '148','name_ar' => 'كاليدونيا الجديدة','name_fr' => 'Nouvelle Calédonie','name_en' => 'New Caledonia','code' => 'country-nc.svg'),
            array('id' => '149','name_ar' => 'النيجر','name_fr' => 'Niger','name_en' => 'Niger','code' => 'country-ne.svg'),
            array('id' => '150','name_ar' => 'جزيرة نورفولك','name_fr' => 'l\'ile de Norfolk','name_en' => 'Norfolk Island','code' => 'country-nf.svg'),
            array('id' => '151','name_ar' => 'نيجيريا','name_fr' => 'Nigeria','name_en' => 'Nigeria','code' => 'country-ng.svg'),
            array('id' => '152','name_ar' => 'نيكاراغوا','name_fr' => 'Nicaragua','name_en' => 'Nicaragua','code' => 'country-ni.svg'),
            array('id' => '153','name_ar' => 'هولندا','name_fr' => 'Pays-Bas','name_en' => 'Netherlands','code' => 'country-nl.svg'),
            array('id' => '154','name_ar' => 'النرويج','name_fr' => 'Norvège','name_en' => 'Norway','code' => 'country-no.svg'),
            array('id' => '155','name_ar' => 'نيبال','name_fr' => 'Népal','name_en' => 'Nepal','code' => 'country-np.svg'),
            array('id' => '156','name_ar' => 'ناورو','name_fr' => 'Nauru','name_en' => 'Nauru','code' => 'country-nr.svg'),
            array('id' => '157','name_ar' => 'نيوي','name_fr' => 'Niue','name_en' => 'Niue','code' => 'country-nu.svg'),
            array('id' => '158','name_ar' => 'نيوزيلندا (اوتياروا)','name_fr' => 'Nouvelle-Zélande (Aotearoa)','name_en' => 'New Zealand (Aotearoa)','code' => 'country-nz.svg'),
            array('id' => '159','name_ar' => 'سلطنة عمان','name_fr' => 'Oman','name_en' => 'Oman','code' => 'country-om.svg'),
            array('id' => '160','name_ar' => 'بناما','name_fr' => 'Panama','name_en' => 'Panama','code' => 'country-pa.svg'),
            array('id' => '161','name_ar' => 'بيرو','name_fr' => 'Pérou','name_en' => 'Peru','code' => 'country-pe.svg'),
            array('id' => '162','name_ar' => 'بولينيزيا الفرنسية','name_fr' => 'Polynésie française','name_en' => 'French Polynesia','code' => 'country-pf.svg'),
            array('id' => '163','name_ar' => 'بابوا غينيا الجديدة','name_fr' => 'Papouasie Nouvelle Guinée','name_en' => 'Papua New Guinea','code' => 'country-pg.svg'),
            array('id' => '164','name_ar' => 'الفلبين','name_fr' => 'Philippines','name_en' => 'Philippines','code' => 'country-ph.svg'),
            array('id' => '165','name_ar' => 'باكستان','name_fr' => 'Pakistan','name_en' => 'Pakistan','code' => 'country-pk.svg'),
            array('id' => '166','name_ar' => 'بولندا','name_fr' => 'Pologne','name_en' => 'Poland','code' => 'country-pl.svg'),
            array('id' => '167','name_ar' => 'سانت بيير وميكلون','name_fr' => 'Saint Pierre et Miquelon','name_en' => 'Saint Pierre and Miquelon','code' => 'country-pm.svg'),
            array('id' => '168','name_ar' => 'بيتكيرن','name_fr' => 'Pitcairn','name_en' => 'Pitcairn','code' => 'country-pn.svg'),
            array('id' => '169','name_ar' => 'الأراضي الفلسطينية','name_fr' => 'Territoire Palestinien','name_en' => 'Palestinian Territory','code' => 'country-ps.svg'),
            array('id' => '170','name_ar' => 'البرتغال','name_fr' => 'le Portugal','name_en' => 'Portugal','code' => 'country-pt.svg'),
            array('id' => '171','name_ar' => 'بالاو','name_fr' => 'Palau','name_en' => 'Palau','code' => 'country-pw.svg'),
            array('id' => '172','name_ar' => 'باراغواي','name_fr' => 'Paraguay','name_en' => 'Paraguay','code' => 'country-py.svg'),
            array('id' => '173','name_ar' => 'دولة قطر','name_fr' => 'Qatar','name_en' => 'Qatar','code' => 'country-qa.svg'),
            array('id' => '174','name_ar' => 'جمع شمل','name_fr' => 'Réunion','name_en' => 'Reunion','code' => 'country-re.svg'),
            array('id' => '175','name_ar' => 'رومانيا','name_fr' => 'Roumanie','name_en' => 'Romania','code' => 'country-ro.svg'),
            array('id' => '176','name_ar' => 'الاتحاد الروسي','name_fr' => 'Fédération Russe','name_en' => 'Russian Federation','code' => 'country-ru.svg'),
            array('id' => '177','name_ar' => 'رواندا','name_fr' => 'Rwanda','name_en' => 'Rwanda','code' => 'country-rw.svg'),
            array('id' => '178','name_ar' => 'المملكة العربية السعودية','name_fr' => 'Arabie Saoudite','name_en' => 'Saudi Arabia','code' => 'country-sa.svg'),
            array('id' => '179','name_ar' => 'جزر سليمان','name_fr' => 'Les îles Salomon','name_en' => 'Solomon Islands','code' => 'country-sb.svg'),
            array('id' => '180','name_ar' => 'سيشيل','name_fr' => 'les Seychelles','name_en' => 'Seychelles','code' => 'country-sc.svg'),
            array('id' => '181','name_ar' => 'سودان','name_fr' => 'Soudan','name_en' => 'Sudan','code' => 'country-sd.svg'),
            array('id' => '182','name_ar' => 'السويد','name_fr' => 'Suède','name_en' => 'Sweden','code' => 'country-se.svg'),
            array('id' => '183','name_ar' => 'سنغافورة','name_fr' => 'Singapour','name_en' => 'Singapore','code' => 'country-sg.svg'),
            array('id' => '184','name_ar' => 'سانت هيلانة','name_fr' => 'Sainte Hélène','name_en' => 'Saint Helena','code' => 'country-sh.svg'),
            array('id' => '185','name_ar' => 'سلوفينيا','name_fr' => 'La slovénie','name_en' => 'Slovenia','code' => 'country-si.svg'),
            array('id' => '186','name_ar' => 'سفالبارد وجان مايان','name_fr' => 'Svalbard et Jan Mayen','name_en' => 'Svalbard and Jan Mayen','code' => 'country-sj.svg'),
            array('id' => '187','name_ar' => 'سلوفاكيا','name_fr' => 'La slovaquie','name_en' => 'Slovakia','code' => 'country-sk.svg'),
            array('id' => '188','name_ar' => 'سيرا ليون','name_fr' => 'Sierra Leone','name_en' => 'Sierra Leone','code' => 'country-sl.svg'),
            array('id' => '189','name_ar' => 'سان مارينو','name_fr' => 'Saint Marin','name_en' => 'San Marino','code' => 'country-sm.svg'),
            array('id' => '190','name_ar' => 'السنغال','name_fr' => 'Sénégal','name_en' => 'Senegal','code' => 'country-sn.svg'),
            array('id' => '191','name_ar' => 'الصومال','name_fr' => 'Somalie','name_en' => 'Somalia','code' => 'country-so.svg'),
            array('id' => '192','name_ar' => 'سورينام','name_fr' => 'Suriname','name_en' => 'Suriname','code' => 'country-sr.svg'),
            array('id' => '193','name_ar' => 'ساو تومي وبرنسيبي','name_fr' => 'Sao Tomé et Principe','name_en' => 'Sao Tome and Principe','code' => 'country-st.svg'),
            array('id' => '194','name_ar' => 'السلفادور','name_fr' => 'Le Salvador','name_en' => 'El Salvador','code' => 'country-sv.svg'),
            array('id' => '195','name_ar' => 'سوريا','name_fr' => 'Syrie','name_en' => 'Syria','code' => 'country-sy.svg'),
            array('id' => '196','name_ar' => 'سوازيلاند','name_fr' => 'Swaziland','name_en' => 'Swaziland','code' => 'country-sz.svg'),
            array('id' => '197','name_ar' => 'جزر تركس وكايكوس','name_fr' => 'îles Turques-et-Caïques','name_en' => 'Turks and Caicos Islands','code' => 'country-tc.svg'),
            array('id' => '198','name_ar' => 'تشاد','name_fr' => 'Le tchad','name_en' => 'Chad','code' => 'country-td.svg'),
            array('id' => '199','name_ar' => 'المناطق الجنوبية لفرنسا','name_fr' => 'Terres australes françaises','name_en' => 'French Southern Territories','code' => 'country-tf.svg'),
            array('id' => '200','name_ar' => 'ليذهب','name_fr' => 'Aller','name_en' => 'Togo','code' => 'country-tg.svg'),
            array('id' => '201','name_ar' => 'تايلاند','name_fr' => 'Thaïlande','name_en' => 'Thailand','code' => 'country-th.svg'),
            array('id' => '202','name_ar' => 'طاجيكستان','name_fr' => 'Tadjikistan','name_en' => 'Tajikistan','code' => 'country-tj.svg'),
            array('id' => '203','name_ar' => 'توكيلاو','name_fr' => 'Tokelau','name_en' => 'Tokelau','code' => 'country-tk.svg'),
            array('id' => '204','name_ar' => 'تركمانستان','name_fr' => 'Turkménistan','name_en' => 'Turkmenistan','code' => 'country-tm.svg'),
            array('id' => '205','name_ar' => 'تونس','name_fr' => 'Tunisie','name_en' => 'Tunisia','code' => 'country-tn.svg'),
            array('id' => '206','name_ar' => 'تونغا','name_fr' => 'Tonga','name_en' => 'Tonga','code' => 'country-to.svg'),
            array('id' => '207','name_ar' => 'ديك رومي','name_fr' => 'dinde','name_en' => 'Turkey','code' => 'country-tr.svg'),
            array('id' => '208','name_ar' => 'ترينداد وتوباغو','name_fr' => 'Trinité-et-Tobago','name_en' => 'Trinidad and Tobago','code' => 'country-tt.svg'),
            array('id' => '209','name_ar' => 'توفالو','name_fr' => 'Tuvalu','name_en' => 'Tuvalu','code' => 'country-tv.svg'),
            array('id' => '210','name_ar' => 'تايوان','name_fr' => 'Taïwan','name_en' => 'Taiwan','code' => 'country-tw.svg'),
            array('id' => '211','name_ar' => 'تنزانيا','name_fr' => 'Tanzanie','name_en' => 'Tanzania','code' => 'country-tz.svg'),
            array('id' => '212','name_ar' => 'أوكرانيا','name_fr' => 'Ukraine','name_en' => 'Ukraine','code' => 'country-ua.svg'),
            array('id' => '213','name_ar' => 'أوغندا','name_fr' => 'Ouganda','name_en' => 'Uganda','code' => 'country-ug.svg'),
            array('id' => '214','name_ar' => 'أوروغواي','name_fr' => 'Uruguay','name_en' => 'Uruguay','code' => 'country-uy.svg'),
            array('id' => '215','name_ar' => 'أوزبكستان','name_fr' => 'Ouzbékistan','name_en' => 'Uzbekistan','code' => 'country-uz.svg'),
            array('id' => '216','name_ar' => 'سانت فنسنت وجزر غرينادين','name_fr' => 'Saint-Vincent-et-les-Grenadines','name_en' => 'Saint Vincent and the Grenadines','code' => 'country-vc.svg'),
            array('id' => '217','name_ar' => 'فنزويلا','name_fr' => 'Venezuela','name_en' => 'Venezuela','code' => 'country-ve.svg'),
            array('id' => '218','name_ar' => 'جزر العذراء البريطانية)','name_fr' => 'Îles vierges britanniques','name_en' => 'Virgin Islands (British)','code' => 'country-vg.svg'),
            array('id' => '219','name_ar' => 'جزر فيرجن (الولايات المتحدة)','name_fr' => 'Îles Vierges (États-Unis)','name_en' => 'Virgin Islands (U.S.)','code' => 'country-vi.svg'),
            array('id' => '220','name_ar' => 'فيتنام','name_fr' => 'Viet Nam','name_en' => 'Viet Nam','code' => 'country-vn.svg'),
            array('id' => '221','name_ar' => 'فانواتو','name_fr' => 'Vanuatu','name_en' => 'Vanuatu','code' => 'country-vu.svg'),
            array('id' => '222','name_ar' => 'واليس وفوتونا','name_fr' => 'Wallis et Futuna','name_en' => 'Wallis and Futuna','code' => 'country-wf.svg'),
            array('id' => '223','name_ar' => 'ساموا','name_fr' => 'Samoa','name_en' => 'Samoa','code' => 'country-ws.svg'),
            array('id' => '224','name_ar' => 'اليمن','name_fr' => 'Yémen','name_en' => 'Yemen','code' => 'country-ye.svg'),
            array('id' => '225','name_ar' => 'مايوت','name_fr' => 'Mayotte','name_en' => 'Mayotte','code' => 'country-yt.svg'),
            array('id' => '226','name_ar' => 'جنوب أفريقيا','name_fr' => 'Afrique du Sud','name_en' => 'South Africa','code' => 'country-za.svg'),
            array('id' => '227','name_ar' => 'زامبيا','name_fr' => 'Zambie','name_en' => 'Zambia','code' => 'country-zm.svg'),
         //   array('id' => '228','name_ar' => 'زائير (سابقة)','name_fr' => 'Zaïre (ancien)','name_en' => 'Zaire (former)','code' => 'country-zr.svg'),
            array('id' => '229','name_ar' => 'زيمبابوي','name_fr' => 'Zimbabwe','name_en' => 'Zimbabwe','code' => 'country-zw.svg'),
            array('id' => '230','name_ar' => 'الولايات المتحدة','name_fr' => 'les États-Unis d\'Amérique','name_en' => 'United States of America','code' => 'country-us.svg'),
         //   array('id' => '231','name_ar' => 'غير معروف','name_fr' => 'unknown','name_en' => 'unknown','code' => 'country-nu.svgll')
            ];





            DB::table('countries')->insert($countries);


    }
}
